mkdir -p /usr/local/lib/OpenPEARLesp32/prj/xtensa
cp build/esp-idf/xtensa/libxtensa.a /usr/local/lib/OpenPEARLesp32/prj/xtensa/libxtensa.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls
cp build/esp-idf/mbedtls/libmbedtls.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/libmbedtls.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/efuse
cp build/esp-idf/efuse/libefuse.a /usr/local/lib/OpenPEARLesp32/prj/efuse/libefuse.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/bootloader_support
cp build/esp-idf/bootloader_support/libbootloader_support.a /usr/local/lib/OpenPEARLesp32/prj/bootloader_support/libbootloader_support.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/app_update
cp build/esp-idf/app_update/libapp_update.a /usr/local/lib/OpenPEARLesp32/prj/app_update/libapp_update.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_ipc
cp build/esp-idf/esp_ipc/libesp_ipc.a /usr/local/lib/OpenPEARLesp32/prj/esp_ipc/libesp_ipc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/spi_flash
cp build/esp-idf/spi_flash/libspi_flash.a /usr/local/lib/OpenPEARLesp32/prj/spi_flash/libspi_flash.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_system
cp build/esp-idf/esp_system/libesp_system.a /usr/local/lib/OpenPEARLesp32/prj/esp_system/libesp_system.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/soc
cp build/esp-idf/soc/libsoc.a /usr/local/lib/OpenPEARLesp32/prj/soc/libsoc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/vfs
cp build/esp-idf/vfs/libvfs.a /usr/local/lib/OpenPEARLesp32/prj/vfs/libvfs.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_eth
cp build/esp-idf/esp_eth/libesp_eth.a /usr/local/lib/OpenPEARLesp32/prj/esp_eth/libesp_eth.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/tcpip_adapter
cp build/esp-idf/tcpip_adapter/libtcpip_adapter.a /usr/local/lib/OpenPEARLesp32/prj/tcpip_adapter/libtcpip_adapter.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_netif
cp build/esp-idf/esp_netif/libesp_netif.a /usr/local/lib/OpenPEARLesp32/prj/esp_netif/libesp_netif.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_event
cp build/esp-idf/esp_event/libesp_event.a /usr/local/lib/OpenPEARLesp32/prj/esp_event/libesp_event.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/wpa_supplicant
cp build/esp-idf/wpa_supplicant/libwpa_supplicant.a /usr/local/lib/OpenPEARLesp32/prj/wpa_supplicant/libwpa_supplicant.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/nvs_flash
cp build/esp-idf/nvs_flash/libnvs_flash.a /usr/local/lib/OpenPEARLesp32/prj/nvs_flash/libnvs_flash.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_wifi
cp build/esp-idf/esp_wifi/libesp_wifi.a /usr/local/lib/OpenPEARLesp32/prj/esp_wifi/libesp_wifi.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/lwip
cp build/esp-idf/lwip/liblwip.a /usr/local/lib/OpenPEARLesp32/prj/lwip/liblwip.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/log
cp build/esp-idf/log/liblog.a /usr/local/lib/OpenPEARLesp32/prj/log/liblog.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/heap
cp build/esp-idf/heap/libheap.a /usr/local/lib/OpenPEARLesp32/prj/heap/libheap.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_ringbuf
cp build/esp-idf/esp_ringbuf/libesp_ringbuf.a /usr/local/lib/OpenPEARLesp32/prj/esp_ringbuf/libesp_ringbuf.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/driver
cp build/esp-idf/driver/libdriver.a /usr/local/lib/OpenPEARLesp32/prj/driver/libdriver.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/pthread
cp build/esp-idf/pthread/libpthread.a /usr/local/lib/OpenPEARLesp32/prj/pthread/libpthread.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/espcoredump
cp build/esp-idf/espcoredump/libespcoredump.a /usr/local/lib/OpenPEARLesp32/prj/espcoredump/libespcoredump.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/perfmon
cp build/esp-idf/perfmon/libperfmon.a /usr/local/lib/OpenPEARLesp32/prj/perfmon/libperfmon.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp32
cp build/esp-idf/esp32/libesp32.a /usr/local/lib/OpenPEARLesp32/prj/esp32/libesp32.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_common
cp build/esp-idf/esp_common/libesp_common.a /usr/local/lib/OpenPEARLesp32/prj/esp_common/libesp_common.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_timer
cp build/esp-idf/esp_timer/libesp_timer.a /usr/local/lib/OpenPEARLesp32/prj/esp_timer/libesp_timer.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/freertos
cp build/esp-idf/freertos/libfreertos.a /usr/local/lib/OpenPEARLesp32/prj/freertos/libfreertos.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/newlib
cp build/esp-idf/newlib/libnewlib.a /usr/local/lib/OpenPEARLesp32/prj/newlib/libnewlib.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/cxx
cp build/esp-idf/cxx/libcxx.a /usr/local/lib/OpenPEARLesp32/prj/cxx/libcxx.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/app_trace
cp build/esp-idf/app_trace/libapp_trace.a /usr/local/lib/OpenPEARLesp32/prj/app_trace/libapp_trace.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/asio
cp build/esp-idf/asio/libasio.a /usr/local/lib/OpenPEARLesp32/prj/asio/libasio.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/cbor
cp build/esp-idf/cbor/libcbor.a /usr/local/lib/OpenPEARLesp32/prj/cbor/libcbor.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/coap
cp build/esp-idf/coap/libcoap.a /usr/local/lib/OpenPEARLesp32/prj/coap/libcoap.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/console
cp build/esp-idf/console/libconsole.a /usr/local/lib/OpenPEARLesp32/prj/console/libconsole.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/nghttp
cp build/esp-idf/nghttp/libnghttp.a /usr/local/lib/OpenPEARLesp32/prj/nghttp/libnghttp.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp-tls
cp build/esp-idf/esp-tls/libesp-tls.a /usr/local/lib/OpenPEARLesp32/prj/esp-tls/libesp-tls.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_adc_cal
cp build/esp-idf/esp_adc_cal/libesp_adc_cal.a /usr/local/lib/OpenPEARLesp32/prj/esp_adc_cal/libesp_adc_cal.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_gdbstub
cp build/esp-idf/esp_gdbstub/libesp_gdbstub.a /usr/local/lib/OpenPEARLesp32/prj/esp_gdbstub/libesp_gdbstub.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_hid
cp build/esp-idf/esp_hid/libesp_hid.a /usr/local/lib/OpenPEARLesp32/prj/esp_hid/libesp_hid.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/tcp_transport
cp build/esp-idf/tcp_transport/libtcp_transport.a /usr/local/lib/OpenPEARLesp32/prj/tcp_transport/libtcp_transport.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_http_client
cp build/esp-idf/esp_http_client/libesp_http_client.a /usr/local/lib/OpenPEARLesp32/prj/esp_http_client/libesp_http_client.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_http_server
cp build/esp-idf/esp_http_server/libesp_http_server.a /usr/local/lib/OpenPEARLesp32/prj/esp_http_server/libesp_http_server.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_https_ota
cp build/esp-idf/esp_https_ota/libesp_https_ota.a /usr/local/lib/OpenPEARLesp32/prj/esp_https_ota/libesp_https_ota.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/protobuf-c
cp build/esp-idf/protobuf-c/libprotobuf-c.a /usr/local/lib/OpenPEARLesp32/prj/protobuf-c/libprotobuf-c.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/protocomm
cp build/esp-idf/protocomm/libprotocomm.a /usr/local/lib/OpenPEARLesp32/prj/protocomm/libprotocomm.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mdns
cp build/esp-idf/mdns/libmdns.a /usr/local/lib/OpenPEARLesp32/prj/mdns/libmdns.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_local_ctrl
cp build/esp-idf/esp_local_ctrl/libesp_local_ctrl.a /usr/local/lib/OpenPEARLesp32/prj/esp_local_ctrl/libesp_local_ctrl.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/sdmmc
cp build/esp-idf/sdmmc/libsdmmc.a /usr/local/lib/OpenPEARLesp32/prj/sdmmc/libsdmmc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_serial_slave_link
cp build/esp-idf/esp_serial_slave_link/libesp_serial_slave_link.a /usr/local/lib/OpenPEARLesp32/prj/esp_serial_slave_link/libesp_serial_slave_link.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_websocket_client
cp build/esp-idf/esp_websocket_client/libesp_websocket_client.a /usr/local/lib/OpenPEARLesp32/prj/esp_websocket_client/libesp_websocket_client.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/expat
cp build/esp-idf/expat/libexpat.a /usr/local/lib/OpenPEARLesp32/prj/expat/libexpat.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/wear_levelling
cp build/esp-idf/wear_levelling/libwear_levelling.a /usr/local/lib/OpenPEARLesp32/prj/wear_levelling/libwear_levelling.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/fatfs
cp build/esp-idf/fatfs/libfatfs.a /usr/local/lib/OpenPEARLesp32/prj/fatfs/libfatfs.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/freemodbus
cp build/esp-idf/freemodbus/libfreemodbus.a /usr/local/lib/OpenPEARLesp32/prj/freemodbus/libfreemodbus.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/jsmn
cp build/esp-idf/jsmn/libjsmn.a /usr/local/lib/OpenPEARLesp32/prj/jsmn/libjsmn.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/json
cp build/esp-idf/json/libjson.a /usr/local/lib/OpenPEARLesp32/prj/json/libjson.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/libsodium
cp build/esp-idf/libsodium/liblibsodium.a /usr/local/lib/OpenPEARLesp32/prj/libsodium/liblibsodium.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mqtt
cp build/esp-idf/mqtt/libmqtt.a /usr/local/lib/OpenPEARLesp32/prj/mqtt/libmqtt.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/openssl
cp build/esp-idf/openssl/libopenssl.a /usr/local/lib/OpenPEARLesp32/prj/openssl/libopenssl.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/spiffs
cp build/esp-idf/spiffs/libspiffs.a /usr/local/lib/OpenPEARLesp32/prj/spiffs/libspiffs.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/ulp
cp build/esp-idf/ulp/libulp.a /usr/local/lib/OpenPEARLesp32/prj/ulp/libulp.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/unity
cp build/esp-idf/unity/libunity.a /usr/local/lib/OpenPEARLesp32/prj/unity/libunity.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/wifi_provisioning
cp build/esp-idf/wifi_provisioning/libwifi_provisioning.a /usr/local/lib/OpenPEARLesp32/prj/wifi_provisioning/libwifi_provisioning.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/main
cp build/esp-idf/main/libmain.a /usr/local/lib/OpenPEARLesp32/prj/main/libmain.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/sdmmc
cp build/esp-idf/sdmmc/libsdmmc.a /usr/local/lib/OpenPEARLesp32/prj/sdmmc/libsdmmc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/wear_levelling
cp build/esp-idf/wear_levelling/libwear_levelling.a /usr/local/lib/OpenPEARLesp32/prj/wear_levelling/libwear_levelling.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/protocomm
cp build/esp-idf/protocomm/libprotocomm.a /usr/local/lib/OpenPEARLesp32/prj/protocomm/libprotocomm.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/protobuf-c
cp build/esp-idf/protobuf-c/libprotobuf-c.a /usr/local/lib/OpenPEARLesp32/prj/protobuf-c/libprotobuf-c.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mdns
cp build/esp-idf/mdns/libmdns.a /usr/local/lib/OpenPEARLesp32/prj/mdns/libmdns.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/console
cp build/esp-idf/console/libconsole.a /usr/local/lib/OpenPEARLesp32/prj/console/libconsole.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/json
cp build/esp-idf/json/libjson.a /usr/local/lib/OpenPEARLesp32/prj/json/libjson.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mqtt
cp build/esp-idf/mqtt/libmqtt.a /usr/local/lib/OpenPEARLesp32/prj/mqtt/libmqtt.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/xtensa
cp build/esp-idf/xtensa/libxtensa.a /usr/local/lib/OpenPEARLesp32/prj/xtensa/libxtensa.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls
cp build/esp-idf/mbedtls/libmbedtls.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/libmbedtls.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/efuse
cp build/esp-idf/efuse/libefuse.a /usr/local/lib/OpenPEARLesp32/prj/efuse/libefuse.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/bootloader_support
cp build/esp-idf/bootloader_support/libbootloader_support.a /usr/local/lib/OpenPEARLesp32/prj/bootloader_support/libbootloader_support.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/app_update
cp build/esp-idf/app_update/libapp_update.a /usr/local/lib/OpenPEARLesp32/prj/app_update/libapp_update.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_ipc
cp build/esp-idf/esp_ipc/libesp_ipc.a /usr/local/lib/OpenPEARLesp32/prj/esp_ipc/libesp_ipc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/spi_flash
cp build/esp-idf/spi_flash/libspi_flash.a /usr/local/lib/OpenPEARLesp32/prj/spi_flash/libspi_flash.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_system
cp build/esp-idf/esp_system/libesp_system.a /usr/local/lib/OpenPEARLesp32/prj/esp_system/libesp_system.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/soc
cp build/esp-idf/soc/libsoc.a /usr/local/lib/OpenPEARLesp32/prj/soc/libsoc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/vfs
cp build/esp-idf/vfs/libvfs.a /usr/local/lib/OpenPEARLesp32/prj/vfs/libvfs.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_eth
cp build/esp-idf/esp_eth/libesp_eth.a /usr/local/lib/OpenPEARLesp32/prj/esp_eth/libesp_eth.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/tcpip_adapter
cp build/esp-idf/tcpip_adapter/libtcpip_adapter.a /usr/local/lib/OpenPEARLesp32/prj/tcpip_adapter/libtcpip_adapter.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_netif
cp build/esp-idf/esp_netif/libesp_netif.a /usr/local/lib/OpenPEARLesp32/prj/esp_netif/libesp_netif.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_event
cp build/esp-idf/esp_event/libesp_event.a /usr/local/lib/OpenPEARLesp32/prj/esp_event/libesp_event.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/wpa_supplicant
cp build/esp-idf/wpa_supplicant/libwpa_supplicant.a /usr/local/lib/OpenPEARLesp32/prj/wpa_supplicant/libwpa_supplicant.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/nvs_flash
cp build/esp-idf/nvs_flash/libnvs_flash.a /usr/local/lib/OpenPEARLesp32/prj/nvs_flash/libnvs_flash.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_wifi
cp build/esp-idf/esp_wifi/libesp_wifi.a /usr/local/lib/OpenPEARLesp32/prj/esp_wifi/libesp_wifi.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/lwip
cp build/esp-idf/lwip/liblwip.a /usr/local/lib/OpenPEARLesp32/prj/lwip/liblwip.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/log
cp build/esp-idf/log/liblog.a /usr/local/lib/OpenPEARLesp32/prj/log/liblog.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/heap
cp build/esp-idf/heap/libheap.a /usr/local/lib/OpenPEARLesp32/prj/heap/libheap.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_ringbuf
cp build/esp-idf/esp_ringbuf/libesp_ringbuf.a /usr/local/lib/OpenPEARLesp32/prj/esp_ringbuf/libesp_ringbuf.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/driver
cp build/esp-idf/driver/libdriver.a /usr/local/lib/OpenPEARLesp32/prj/driver/libdriver.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/pthread
cp build/esp-idf/pthread/libpthread.a /usr/local/lib/OpenPEARLesp32/prj/pthread/libpthread.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/espcoredump
cp build/esp-idf/espcoredump/libespcoredump.a /usr/local/lib/OpenPEARLesp32/prj/espcoredump/libespcoredump.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/perfmon
cp build/esp-idf/perfmon/libperfmon.a /usr/local/lib/OpenPEARLesp32/prj/perfmon/libperfmon.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp32
cp build/esp-idf/esp32/libesp32.a /usr/local/lib/OpenPEARLesp32/prj/esp32/libesp32.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_common
cp build/esp-idf/esp_common/libesp_common.a /usr/local/lib/OpenPEARLesp32/prj/esp_common/libesp_common.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_timer
cp build/esp-idf/esp_timer/libesp_timer.a /usr/local/lib/OpenPEARLesp32/prj/esp_timer/libesp_timer.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/freertos
cp build/esp-idf/freertos/libfreertos.a /usr/local/lib/OpenPEARLesp32/prj/freertos/libfreertos.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/newlib
cp build/esp-idf/newlib/libnewlib.a /usr/local/lib/OpenPEARLesp32/prj/newlib/libnewlib.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/cxx
cp build/esp-idf/cxx/libcxx.a /usr/local/lib/OpenPEARLesp32/prj/cxx/libcxx.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/app_trace
cp build/esp-idf/app_trace/libapp_trace.a /usr/local/lib/OpenPEARLesp32/prj/app_trace/libapp_trace.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/nghttp
cp build/esp-idf/nghttp/libnghttp.a /usr/local/lib/OpenPEARLesp32/prj/nghttp/libnghttp.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp-tls
cp build/esp-idf/esp-tls/libesp-tls.a /usr/local/lib/OpenPEARLesp32/prj/esp-tls/libesp-tls.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/tcp_transport
cp build/esp-idf/tcp_transport/libtcp_transport.a /usr/local/lib/OpenPEARLesp32/prj/tcp_transport/libtcp_transport.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_http_client
cp build/esp-idf/esp_http_client/libesp_http_client.a /usr/local/lib/OpenPEARLesp32/prj/esp_http_client/libesp_http_client.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_http_server
cp build/esp-idf/esp_http_server/libesp_http_server.a /usr/local/lib/OpenPEARLesp32/prj/esp_http_server/libesp_http_server.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/ulp
cp build/esp-idf/ulp/libulp.a /usr/local/lib/OpenPEARLesp32/prj/ulp/libulp.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library
cp build/esp-idf/mbedtls/mbedtls/library/libmbedtls.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedtls.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library
cp build/esp-idf/mbedtls/mbedtls/library/libmbedcrypto.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedcrypto.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library
cp build/esp-idf/mbedtls/mbedtls/library/libmbedx509.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedx509.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/soc/soc/esp32
cp build/esp-idf/soc/soc/esp32/libsoc_esp32.a /usr/local/lib/OpenPEARLesp32/prj/soc/soc/esp32/libsoc_esp32.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libcoexist.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcoexist.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libcore.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcore.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libespnow.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libespnow.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libmesh.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libmesh.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libnet80211.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libnet80211.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libpp.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libpp.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/librtc.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/librtc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libsmartconfig.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libsmartconfig.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libphy.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libphy.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/xtensa
cp build/esp-idf/xtensa/libxtensa.a /usr/local/lib/OpenPEARLesp32/prj/xtensa/libxtensa.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls
cp build/esp-idf/mbedtls/libmbedtls.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/libmbedtls.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/efuse
cp build/esp-idf/efuse/libefuse.a /usr/local/lib/OpenPEARLesp32/prj/efuse/libefuse.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/bootloader_support
cp build/esp-idf/bootloader_support/libbootloader_support.a /usr/local/lib/OpenPEARLesp32/prj/bootloader_support/libbootloader_support.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/app_update
cp build/esp-idf/app_update/libapp_update.a /usr/local/lib/OpenPEARLesp32/prj/app_update/libapp_update.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_ipc
cp build/esp-idf/esp_ipc/libesp_ipc.a /usr/local/lib/OpenPEARLesp32/prj/esp_ipc/libesp_ipc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/spi_flash
cp build/esp-idf/spi_flash/libspi_flash.a /usr/local/lib/OpenPEARLesp32/prj/spi_flash/libspi_flash.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_system
cp build/esp-idf/esp_system/libesp_system.a /usr/local/lib/OpenPEARLesp32/prj/esp_system/libesp_system.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/soc
cp build/esp-idf/soc/libsoc.a /usr/local/lib/OpenPEARLesp32/prj/soc/libsoc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/vfs
cp build/esp-idf/vfs/libvfs.a /usr/local/lib/OpenPEARLesp32/prj/vfs/libvfs.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_eth
cp build/esp-idf/esp_eth/libesp_eth.a /usr/local/lib/OpenPEARLesp32/prj/esp_eth/libesp_eth.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/tcpip_adapter
cp build/esp-idf/tcpip_adapter/libtcpip_adapter.a /usr/local/lib/OpenPEARLesp32/prj/tcpip_adapter/libtcpip_adapter.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_netif
cp build/esp-idf/esp_netif/libesp_netif.a /usr/local/lib/OpenPEARLesp32/prj/esp_netif/libesp_netif.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_event
cp build/esp-idf/esp_event/libesp_event.a /usr/local/lib/OpenPEARLesp32/prj/esp_event/libesp_event.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/wpa_supplicant
cp build/esp-idf/wpa_supplicant/libwpa_supplicant.a /usr/local/lib/OpenPEARLesp32/prj/wpa_supplicant/libwpa_supplicant.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/nvs_flash
cp build/esp-idf/nvs_flash/libnvs_flash.a /usr/local/lib/OpenPEARLesp32/prj/nvs_flash/libnvs_flash.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_wifi
cp build/esp-idf/esp_wifi/libesp_wifi.a /usr/local/lib/OpenPEARLesp32/prj/esp_wifi/libesp_wifi.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/lwip
cp build/esp-idf/lwip/liblwip.a /usr/local/lib/OpenPEARLesp32/prj/lwip/liblwip.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/log
cp build/esp-idf/log/liblog.a /usr/local/lib/OpenPEARLesp32/prj/log/liblog.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/heap
cp build/esp-idf/heap/libheap.a /usr/local/lib/OpenPEARLesp32/prj/heap/libheap.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_ringbuf
cp build/esp-idf/esp_ringbuf/libesp_ringbuf.a /usr/local/lib/OpenPEARLesp32/prj/esp_ringbuf/libesp_ringbuf.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/driver
cp build/esp-idf/driver/libdriver.a /usr/local/lib/OpenPEARLesp32/prj/driver/libdriver.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/pthread
cp build/esp-idf/pthread/libpthread.a /usr/local/lib/OpenPEARLesp32/prj/pthread/libpthread.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/espcoredump
cp build/esp-idf/espcoredump/libespcoredump.a /usr/local/lib/OpenPEARLesp32/prj/espcoredump/libespcoredump.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/perfmon
cp build/esp-idf/perfmon/libperfmon.a /usr/local/lib/OpenPEARLesp32/prj/perfmon/libperfmon.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp32
cp build/esp-idf/esp32/libesp32.a /usr/local/lib/OpenPEARLesp32/prj/esp32/libesp32.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_common
cp build/esp-idf/esp_common/libesp_common.a /usr/local/lib/OpenPEARLesp32/prj/esp_common/libesp_common.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_timer
cp build/esp-idf/esp_timer/libesp_timer.a /usr/local/lib/OpenPEARLesp32/prj/esp_timer/libesp_timer.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/freertos
cp build/esp-idf/freertos/libfreertos.a /usr/local/lib/OpenPEARLesp32/prj/freertos/libfreertos.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/newlib
cp build/esp-idf/newlib/libnewlib.a /usr/local/lib/OpenPEARLesp32/prj/newlib/libnewlib.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/cxx
cp build/esp-idf/cxx/libcxx.a /usr/local/lib/OpenPEARLesp32/prj/cxx/libcxx.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/app_trace
cp build/esp-idf/app_trace/libapp_trace.a /usr/local/lib/OpenPEARLesp32/prj/app_trace/libapp_trace.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/nghttp
cp build/esp-idf/nghttp/libnghttp.a /usr/local/lib/OpenPEARLesp32/prj/nghttp/libnghttp.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp-tls
cp build/esp-idf/esp-tls/libesp-tls.a /usr/local/lib/OpenPEARLesp32/prj/esp-tls/libesp-tls.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/tcp_transport
cp build/esp-idf/tcp_transport/libtcp_transport.a /usr/local/lib/OpenPEARLesp32/prj/tcp_transport/libtcp_transport.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_http_client
cp build/esp-idf/esp_http_client/libesp_http_client.a /usr/local/lib/OpenPEARLesp32/prj/esp_http_client/libesp_http_client.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_http_server
cp build/esp-idf/esp_http_server/libesp_http_server.a /usr/local/lib/OpenPEARLesp32/prj/esp_http_server/libesp_http_server.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/ulp
cp build/esp-idf/ulp/libulp.a /usr/local/lib/OpenPEARLesp32/prj/ulp/libulp.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library
cp build/esp-idf/mbedtls/mbedtls/library/libmbedtls.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedtls.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library
cp build/esp-idf/mbedtls/mbedtls/library/libmbedcrypto.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedcrypto.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library
cp build/esp-idf/mbedtls/mbedtls/library/libmbedx509.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedx509.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/soc/soc/esp32
cp build/esp-idf/soc/soc/esp32/libsoc_esp32.a /usr/local/lib/OpenPEARLesp32/prj/soc/soc/esp32/libsoc_esp32.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libcoexist.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcoexist.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libcore.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcore.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libespnow.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libespnow.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libmesh.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libmesh.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libnet80211.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libnet80211.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libpp.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libpp.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/librtc.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/librtc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libsmartconfig.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libsmartconfig.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libphy.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libphy.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/xtensa
cp build/esp-idf/xtensa/libxtensa.a /usr/local/lib/OpenPEARLesp32/prj/xtensa/libxtensa.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls
cp build/esp-idf/mbedtls/libmbedtls.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/libmbedtls.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/efuse
cp build/esp-idf/efuse/libefuse.a /usr/local/lib/OpenPEARLesp32/prj/efuse/libefuse.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/bootloader_support
cp build/esp-idf/bootloader_support/libbootloader_support.a /usr/local/lib/OpenPEARLesp32/prj/bootloader_support/libbootloader_support.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/app_update
cp build/esp-idf/app_update/libapp_update.a /usr/local/lib/OpenPEARLesp32/prj/app_update/libapp_update.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_ipc
cp build/esp-idf/esp_ipc/libesp_ipc.a /usr/local/lib/OpenPEARLesp32/prj/esp_ipc/libesp_ipc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/spi_flash
cp build/esp-idf/spi_flash/libspi_flash.a /usr/local/lib/OpenPEARLesp32/prj/spi_flash/libspi_flash.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_system
cp build/esp-idf/esp_system/libesp_system.a /usr/local/lib/OpenPEARLesp32/prj/esp_system/libesp_system.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/soc
cp build/esp-idf/soc/libsoc.a /usr/local/lib/OpenPEARLesp32/prj/soc/libsoc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/vfs
cp build/esp-idf/vfs/libvfs.a /usr/local/lib/OpenPEARLesp32/prj/vfs/libvfs.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_eth
cp build/esp-idf/esp_eth/libesp_eth.a /usr/local/lib/OpenPEARLesp32/prj/esp_eth/libesp_eth.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/tcpip_adapter
cp build/esp-idf/tcpip_adapter/libtcpip_adapter.a /usr/local/lib/OpenPEARLesp32/prj/tcpip_adapter/libtcpip_adapter.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_netif
cp build/esp-idf/esp_netif/libesp_netif.a /usr/local/lib/OpenPEARLesp32/prj/esp_netif/libesp_netif.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_event
cp build/esp-idf/esp_event/libesp_event.a /usr/local/lib/OpenPEARLesp32/prj/esp_event/libesp_event.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/wpa_supplicant
cp build/esp-idf/wpa_supplicant/libwpa_supplicant.a /usr/local/lib/OpenPEARLesp32/prj/wpa_supplicant/libwpa_supplicant.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/nvs_flash
cp build/esp-idf/nvs_flash/libnvs_flash.a /usr/local/lib/OpenPEARLesp32/prj/nvs_flash/libnvs_flash.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_wifi
cp build/esp-idf/esp_wifi/libesp_wifi.a /usr/local/lib/OpenPEARLesp32/prj/esp_wifi/libesp_wifi.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/lwip
cp build/esp-idf/lwip/liblwip.a /usr/local/lib/OpenPEARLesp32/prj/lwip/liblwip.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/log
cp build/esp-idf/log/liblog.a /usr/local/lib/OpenPEARLesp32/prj/log/liblog.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/heap
cp build/esp-idf/heap/libheap.a /usr/local/lib/OpenPEARLesp32/prj/heap/libheap.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_ringbuf
cp build/esp-idf/esp_ringbuf/libesp_ringbuf.a /usr/local/lib/OpenPEARLesp32/prj/esp_ringbuf/libesp_ringbuf.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/driver
cp build/esp-idf/driver/libdriver.a /usr/local/lib/OpenPEARLesp32/prj/driver/libdriver.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/pthread
cp build/esp-idf/pthread/libpthread.a /usr/local/lib/OpenPEARLesp32/prj/pthread/libpthread.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/espcoredump
cp build/esp-idf/espcoredump/libespcoredump.a /usr/local/lib/OpenPEARLesp32/prj/espcoredump/libespcoredump.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/perfmon
cp build/esp-idf/perfmon/libperfmon.a /usr/local/lib/OpenPEARLesp32/prj/perfmon/libperfmon.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp32
cp build/esp-idf/esp32/libesp32.a /usr/local/lib/OpenPEARLesp32/prj/esp32/libesp32.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_common
cp build/esp-idf/esp_common/libesp_common.a /usr/local/lib/OpenPEARLesp32/prj/esp_common/libesp_common.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_timer
cp build/esp-idf/esp_timer/libesp_timer.a /usr/local/lib/OpenPEARLesp32/prj/esp_timer/libesp_timer.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/freertos
cp build/esp-idf/freertos/libfreertos.a /usr/local/lib/OpenPEARLesp32/prj/freertos/libfreertos.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/newlib
cp build/esp-idf/newlib/libnewlib.a /usr/local/lib/OpenPEARLesp32/prj/newlib/libnewlib.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/cxx
cp build/esp-idf/cxx/libcxx.a /usr/local/lib/OpenPEARLesp32/prj/cxx/libcxx.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/app_trace
cp build/esp-idf/app_trace/libapp_trace.a /usr/local/lib/OpenPEARLesp32/prj/app_trace/libapp_trace.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/nghttp
cp build/esp-idf/nghttp/libnghttp.a /usr/local/lib/OpenPEARLesp32/prj/nghttp/libnghttp.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp-tls
cp build/esp-idf/esp-tls/libesp-tls.a /usr/local/lib/OpenPEARLesp32/prj/esp-tls/libesp-tls.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/tcp_transport
cp build/esp-idf/tcp_transport/libtcp_transport.a /usr/local/lib/OpenPEARLesp32/prj/tcp_transport/libtcp_transport.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_http_client
cp build/esp-idf/esp_http_client/libesp_http_client.a /usr/local/lib/OpenPEARLesp32/prj/esp_http_client/libesp_http_client.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_http_server
cp build/esp-idf/esp_http_server/libesp_http_server.a /usr/local/lib/OpenPEARLesp32/prj/esp_http_server/libesp_http_server.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/ulp
cp build/esp-idf/ulp/libulp.a /usr/local/lib/OpenPEARLesp32/prj/ulp/libulp.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library
cp build/esp-idf/mbedtls/mbedtls/library/libmbedtls.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedtls.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library
cp build/esp-idf/mbedtls/mbedtls/library/libmbedcrypto.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedcrypto.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library
cp build/esp-idf/mbedtls/mbedtls/library/libmbedx509.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedx509.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/soc/soc/esp32
cp build/esp-idf/soc/soc/esp32/libsoc_esp32.a /usr/local/lib/OpenPEARLesp32/prj/soc/soc/esp32/libsoc_esp32.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libcoexist.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcoexist.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libcore.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcore.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libespnow.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libespnow.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libmesh.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libmesh.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libnet80211.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libnet80211.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libpp.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libpp.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/librtc.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/librtc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libsmartconfig.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libsmartconfig.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libphy.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libphy.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/xtensa
cp build/esp-idf/xtensa/libxtensa.a /usr/local/lib/OpenPEARLesp32/prj/xtensa/libxtensa.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls
cp build/esp-idf/mbedtls/libmbedtls.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/libmbedtls.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/efuse
cp build/esp-idf/efuse/libefuse.a /usr/local/lib/OpenPEARLesp32/prj/efuse/libefuse.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/bootloader_support
cp build/esp-idf/bootloader_support/libbootloader_support.a /usr/local/lib/OpenPEARLesp32/prj/bootloader_support/libbootloader_support.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/app_update
cp build/esp-idf/app_update/libapp_update.a /usr/local/lib/OpenPEARLesp32/prj/app_update/libapp_update.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_ipc
cp build/esp-idf/esp_ipc/libesp_ipc.a /usr/local/lib/OpenPEARLesp32/prj/esp_ipc/libesp_ipc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/spi_flash
cp build/esp-idf/spi_flash/libspi_flash.a /usr/local/lib/OpenPEARLesp32/prj/spi_flash/libspi_flash.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_system
cp build/esp-idf/esp_system/libesp_system.a /usr/local/lib/OpenPEARLesp32/prj/esp_system/libesp_system.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/soc
cp build/esp-idf/soc/libsoc.a /usr/local/lib/OpenPEARLesp32/prj/soc/libsoc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/vfs
cp build/esp-idf/vfs/libvfs.a /usr/local/lib/OpenPEARLesp32/prj/vfs/libvfs.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_eth
cp build/esp-idf/esp_eth/libesp_eth.a /usr/local/lib/OpenPEARLesp32/prj/esp_eth/libesp_eth.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/tcpip_adapter
cp build/esp-idf/tcpip_adapter/libtcpip_adapter.a /usr/local/lib/OpenPEARLesp32/prj/tcpip_adapter/libtcpip_adapter.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_netif
cp build/esp-idf/esp_netif/libesp_netif.a /usr/local/lib/OpenPEARLesp32/prj/esp_netif/libesp_netif.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_event
cp build/esp-idf/esp_event/libesp_event.a /usr/local/lib/OpenPEARLesp32/prj/esp_event/libesp_event.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/wpa_supplicant
cp build/esp-idf/wpa_supplicant/libwpa_supplicant.a /usr/local/lib/OpenPEARLesp32/prj/wpa_supplicant/libwpa_supplicant.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/nvs_flash
cp build/esp-idf/nvs_flash/libnvs_flash.a /usr/local/lib/OpenPEARLesp32/prj/nvs_flash/libnvs_flash.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_wifi
cp build/esp-idf/esp_wifi/libesp_wifi.a /usr/local/lib/OpenPEARLesp32/prj/esp_wifi/libesp_wifi.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/lwip
cp build/esp-idf/lwip/liblwip.a /usr/local/lib/OpenPEARLesp32/prj/lwip/liblwip.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/log
cp build/esp-idf/log/liblog.a /usr/local/lib/OpenPEARLesp32/prj/log/liblog.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/heap
cp build/esp-idf/heap/libheap.a /usr/local/lib/OpenPEARLesp32/prj/heap/libheap.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_ringbuf
cp build/esp-idf/esp_ringbuf/libesp_ringbuf.a /usr/local/lib/OpenPEARLesp32/prj/esp_ringbuf/libesp_ringbuf.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/driver
cp build/esp-idf/driver/libdriver.a /usr/local/lib/OpenPEARLesp32/prj/driver/libdriver.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/pthread
cp build/esp-idf/pthread/libpthread.a /usr/local/lib/OpenPEARLesp32/prj/pthread/libpthread.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/espcoredump
cp build/esp-idf/espcoredump/libespcoredump.a /usr/local/lib/OpenPEARLesp32/prj/espcoredump/libespcoredump.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/perfmon
cp build/esp-idf/perfmon/libperfmon.a /usr/local/lib/OpenPEARLesp32/prj/perfmon/libperfmon.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp32
cp build/esp-idf/esp32/libesp32.a /usr/local/lib/OpenPEARLesp32/prj/esp32/libesp32.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_common
cp build/esp-idf/esp_common/libesp_common.a /usr/local/lib/OpenPEARLesp32/prj/esp_common/libesp_common.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_timer
cp build/esp-idf/esp_timer/libesp_timer.a /usr/local/lib/OpenPEARLesp32/prj/esp_timer/libesp_timer.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/freertos
cp build/esp-idf/freertos/libfreertos.a /usr/local/lib/OpenPEARLesp32/prj/freertos/libfreertos.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/newlib
cp build/esp-idf/newlib/libnewlib.a /usr/local/lib/OpenPEARLesp32/prj/newlib/libnewlib.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/cxx
cp build/esp-idf/cxx/libcxx.a /usr/local/lib/OpenPEARLesp32/prj/cxx/libcxx.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/app_trace
cp build/esp-idf/app_trace/libapp_trace.a /usr/local/lib/OpenPEARLesp32/prj/app_trace/libapp_trace.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/nghttp
cp build/esp-idf/nghttp/libnghttp.a /usr/local/lib/OpenPEARLesp32/prj/nghttp/libnghttp.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp-tls
cp build/esp-idf/esp-tls/libesp-tls.a /usr/local/lib/OpenPEARLesp32/prj/esp-tls/libesp-tls.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/tcp_transport
cp build/esp-idf/tcp_transport/libtcp_transport.a /usr/local/lib/OpenPEARLesp32/prj/tcp_transport/libtcp_transport.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_http_client
cp build/esp-idf/esp_http_client/libesp_http_client.a /usr/local/lib/OpenPEARLesp32/prj/esp_http_client/libesp_http_client.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp_http_server
cp build/esp-idf/esp_http_server/libesp_http_server.a /usr/local/lib/OpenPEARLesp32/prj/esp_http_server/libesp_http_server.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/ulp
cp build/esp-idf/ulp/libulp.a /usr/local/lib/OpenPEARLesp32/prj/ulp/libulp.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library
cp build/esp-idf/mbedtls/mbedtls/library/libmbedtls.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedtls.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library
cp build/esp-idf/mbedtls/mbedtls/library/libmbedcrypto.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedcrypto.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library
cp build/esp-idf/mbedtls/mbedtls/library/libmbedx509.a /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedx509.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/soc/soc/esp32
cp build/esp-idf/soc/soc/esp32/libsoc_esp32.a /usr/local/lib/OpenPEARLesp32/prj/soc/soc/esp32/libsoc_esp32.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libcoexist.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcoexist.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libcore.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcore.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libespnow.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libespnow.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libmesh.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libmesh.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libnet80211.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libnet80211.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libpp.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libpp.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/librtc.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/librtc.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libsmartconfig.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libsmartconfig.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32
cp /home/mueller/esp/esp-idf/components/esp_wifi/lib/esp32/libphy.a /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libphy.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/xtensa/esp32
cp /home/mueller/esp/esp-idf/components/xtensa/esp32/libhal.a /usr/local/lib/OpenPEARLesp32/idf/xtensa/esp32/libhal.a
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_rom/esp32/ld
 cp /home/mueller/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-time.ld /usr/local/lib/OpenPEARLesp32/idf/esp_rom/esp32/ld/esp32.rom.newlib-time.ld
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_rom/esp32/ld
 cp /home/mueller/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.ld /usr/local/lib/OpenPEARLesp32/idf/esp_rom/esp32/ld/esp32.rom.ld
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_rom/esp32/ld
 cp /home/mueller/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.libgcc.ld /usr/local/lib/OpenPEARLesp32/idf/esp_rom/esp32/ld/esp32.rom.libgcc.ld
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_rom/esp32/ld
 cp /home/mueller/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-data.ld /usr/local/lib/OpenPEARLesp32/idf/esp_rom/esp32/ld/esp32.rom.newlib-data.ld
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_rom/esp32/ld
 cp /home/mueller/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.syscalls.ld /usr/local/lib/OpenPEARLesp32/idf/esp_rom/esp32/ld/esp32.rom.syscalls.ld
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp_rom/esp32/ld
 cp /home/mueller/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-funcs.ld /usr/local/lib/OpenPEARLesp32/idf/esp_rom/esp32/ld/esp32.rom.newlib-funcs.ld
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp32
 cp /home/mueller/OpenPEARL/openpearl-code/runtime/esp32/OpenPEARLProject/build/esp-idf/esp32/esp32_out.ld /usr/local/lib/OpenPEARLesp32/prj/esp32/esp32_out.ld
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/esp32/ld
 cp /home/mueller/OpenPEARL/openpearl-code/runtime/esp32/OpenPEARLProject/build/esp-idf/esp32/ld/esp32.project.ld /usr/local/lib/OpenPEARLesp32/prj/esp32/ld/esp32.project.ld
mkdir -p /usr/local/lib/OpenPEARLesp32/idf/esp32/ld
 cp /home/mueller/esp/esp-idf/components/esp32/ld/esp32.peripherals.ld /usr/local/lib/OpenPEARLesp32/idf/esp32/ld/esp32.peripherals.ld
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/newlib
cp build/esp-idf/newlib/libnewlib.a /usr/local/lib/OpenPEARLesp32/prj/newlib/libnewlib.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/pthread
cp build/esp-idf/pthread/libpthread.a /usr/local/lib/OpenPEARLesp32/prj/pthread/libpthread.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/app_trace
cp build/esp-idf/app_trace/libapp_trace.a /usr/local/lib/OpenPEARLesp32/prj/app_trace/libapp_trace.a
mkdir -p /usr/local/lib/OpenPEARLesp32/prj/app_trace
cp build/esp-idf/app_trace/libapp_trace.a /usr/local/lib/OpenPEARLesp32/prj/app_trace/libapp_trace.a
