CXX=/home/mueller/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++

LINK_PARAMETERS_1= -mlongcalls\
 -Wno-frame-address\

LINK_PARAMETERS_2= /usr/local/lib/OpenPEARLesp32/prj/xtensa/libxtensa.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/libmbedtls.a \
 /usr/local/lib/OpenPEARLesp32/prj/efuse/libefuse.a \
 /usr/local/lib/OpenPEARLesp32/prj/bootloader_support/libbootloader_support.a \
 /usr/local/lib/OpenPEARLesp32/prj/app_update/libapp_update.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_ipc/libesp_ipc.a \
 /usr/local/lib/OpenPEARLesp32/prj/spi_flash/libspi_flash.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_system/libesp_system.a \
 /usr/local/lib/OpenPEARLesp32/prj/soc/libsoc.a \
 /usr/local/lib/OpenPEARLesp32/prj/vfs/libvfs.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_eth/libesp_eth.a \
 /usr/local/lib/OpenPEARLesp32/prj/tcpip_adapter/libtcpip_adapter.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_netif/libesp_netif.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_event/libesp_event.a \
 /usr/local/lib/OpenPEARLesp32/prj/wpa_supplicant/libwpa_supplicant.a \
 /usr/local/lib/OpenPEARLesp32/prj/nvs_flash/libnvs_flash.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_wifi/libesp_wifi.a \
 /usr/local/lib/OpenPEARLesp32/prj/lwip/liblwip.a \
 /usr/local/lib/OpenPEARLesp32/prj/log/liblog.a \
 /usr/local/lib/OpenPEARLesp32/prj/heap/libheap.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_ringbuf/libesp_ringbuf.a \
 /usr/local/lib/OpenPEARLesp32/prj/driver/libdriver.a \
 /usr/local/lib/OpenPEARLesp32/prj/pthread/libpthread.a \
 /usr/local/lib/OpenPEARLesp32/prj/espcoredump/libespcoredump.a \
 /usr/local/lib/OpenPEARLesp32/prj/perfmon/libperfmon.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp32/libesp32.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_common/libesp_common.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_timer/libesp_timer.a \
 /usr/local/lib/OpenPEARLesp32/prj/freertos/libfreertos.a \
 /usr/local/lib/OpenPEARLesp32/prj/newlib/libnewlib.a \
 /usr/local/lib/OpenPEARLesp32/prj/cxx/libcxx.a \
 /usr/local/lib/OpenPEARLesp32/prj/app_trace/libapp_trace.a \
 /usr/local/lib/OpenPEARLesp32/prj/asio/libasio.a \
 /usr/local/lib/OpenPEARLesp32/prj/cbor/libcbor.a \
 /usr/local/lib/OpenPEARLesp32/prj/coap/libcoap.a \
 /usr/local/lib/OpenPEARLesp32/prj/console/libconsole.a \
 /usr/local/lib/OpenPEARLesp32/prj/nghttp/libnghttp.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp-tls/libesp-tls.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_adc_cal/libesp_adc_cal.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_gdbstub/libesp_gdbstub.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_hid/libesp_hid.a \
 /usr/local/lib/OpenPEARLesp32/prj/tcp_transport/libtcp_transport.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_http_client/libesp_http_client.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_http_server/libesp_http_server.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_https_ota/libesp_https_ota.a \
 /usr/local/lib/OpenPEARLesp32/prj/protobuf-c/libprotobuf-c.a \
 /usr/local/lib/OpenPEARLesp32/prj/protocomm/libprotocomm.a \
 /usr/local/lib/OpenPEARLesp32/prj/mdns/libmdns.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_local_ctrl/libesp_local_ctrl.a \
 /usr/local/lib/OpenPEARLesp32/prj/sdmmc/libsdmmc.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_serial_slave_link/libesp_serial_slave_link.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_websocket_client/libesp_websocket_client.a \
 /usr/local/lib/OpenPEARLesp32/prj/expat/libexpat.a \
 /usr/local/lib/OpenPEARLesp32/prj/wear_levelling/libwear_levelling.a \
 /usr/local/lib/OpenPEARLesp32/prj/fatfs/libfatfs.a \
 /usr/local/lib/OpenPEARLesp32/prj/freemodbus/libfreemodbus.a \
 /usr/local/lib/OpenPEARLesp32/prj/jsmn/libjsmn.a \
 /usr/local/lib/OpenPEARLesp32/prj/json/libjson.a \
 /usr/local/lib/OpenPEARLesp32/prj/libsodium/liblibsodium.a \
 /usr/local/lib/OpenPEARLesp32/prj/mqtt/libmqtt.a \
 /usr/local/lib/OpenPEARLesp32/prj/openssl/libopenssl.a \
 /usr/local/lib/OpenPEARLesp32/prj/spiffs/libspiffs.a \
 /usr/local/lib/OpenPEARLesp32/prj/ulp/libulp.a \
 /usr/local/lib/OpenPEARLesp32/prj/unity/libunity.a \
 /usr/local/lib/OpenPEARLesp32/prj/wifi_provisioning/libwifi_provisioning.a \
 /usr/local/lib/OpenPEARLesp32/prj/main/libmain.a \
 -fno-rtti\
 -fno-lto\
 /usr/local/lib/OpenPEARLesp32/prj/sdmmc/libsdmmc.a \
 /usr/local/lib/OpenPEARLesp32/prj/wear_levelling/libwear_levelling.a \
 /usr/local/lib/OpenPEARLesp32/prj/protocomm/libprotocomm.a \
 /usr/local/lib/OpenPEARLesp32/prj/protobuf-c/libprotobuf-c.a \
 /usr/local/lib/OpenPEARLesp32/prj/mdns/libmdns.a \
 /usr/local/lib/OpenPEARLesp32/prj/console/libconsole.a \
 /usr/local/lib/OpenPEARLesp32/prj/json/libjson.a \
 /usr/local/lib/OpenPEARLesp32/prj/mqtt/libmqtt.a \
 /usr/local/lib/OpenPEARLesp32/prj/xtensa/libxtensa.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/libmbedtls.a \
 /usr/local/lib/OpenPEARLesp32/prj/efuse/libefuse.a \
 /usr/local/lib/OpenPEARLesp32/prj/bootloader_support/libbootloader_support.a \
 /usr/local/lib/OpenPEARLesp32/prj/app_update/libapp_update.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_ipc/libesp_ipc.a \
 /usr/local/lib/OpenPEARLesp32/prj/spi_flash/libspi_flash.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_system/libesp_system.a \
 /usr/local/lib/OpenPEARLesp32/prj/soc/libsoc.a \
 /usr/local/lib/OpenPEARLesp32/prj/vfs/libvfs.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_eth/libesp_eth.a \
 /usr/local/lib/OpenPEARLesp32/prj/tcpip_adapter/libtcpip_adapter.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_netif/libesp_netif.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_event/libesp_event.a \
 /usr/local/lib/OpenPEARLesp32/prj/wpa_supplicant/libwpa_supplicant.a \
 /usr/local/lib/OpenPEARLesp32/prj/nvs_flash/libnvs_flash.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_wifi/libesp_wifi.a \
 /usr/local/lib/OpenPEARLesp32/prj/lwip/liblwip.a \
 /usr/local/lib/OpenPEARLesp32/prj/log/liblog.a \
 /usr/local/lib/OpenPEARLesp32/prj/heap/libheap.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_ringbuf/libesp_ringbuf.a \
 /usr/local/lib/OpenPEARLesp32/prj/driver/libdriver.a \
 /usr/local/lib/OpenPEARLesp32/prj/pthread/libpthread.a \
 /usr/local/lib/OpenPEARLesp32/prj/espcoredump/libespcoredump.a \
 /usr/local/lib/OpenPEARLesp32/prj/perfmon/libperfmon.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp32/libesp32.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_common/libesp_common.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_timer/libesp_timer.a \
 /usr/local/lib/OpenPEARLesp32/prj/freertos/libfreertos.a \
 /usr/local/lib/OpenPEARLesp32/prj/newlib/libnewlib.a \
 /usr/local/lib/OpenPEARLesp32/prj/cxx/libcxx.a \
 /usr/local/lib/OpenPEARLesp32/prj/app_trace/libapp_trace.a \
 /usr/local/lib/OpenPEARLesp32/prj/nghttp/libnghttp.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp-tls/libesp-tls.a \
 /usr/local/lib/OpenPEARLesp32/prj/tcp_transport/libtcp_transport.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_http_client/libesp_http_client.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_http_server/libesp_http_server.a \
 /usr/local/lib/OpenPEARLesp32/prj/ulp/libulp.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedtls.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedcrypto.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedx509.a \
 /usr/local/lib/OpenPEARLesp32/prj/soc/soc/esp32/libsoc_esp32.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcoexist.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcore.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libespnow.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libmesh.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libnet80211.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libpp.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/librtc.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libsmartconfig.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libphy.a \
 /usr/local/lib/OpenPEARLesp32/prj/xtensa/libxtensa.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/libmbedtls.a \
 /usr/local/lib/OpenPEARLesp32/prj/efuse/libefuse.a \
 /usr/local/lib/OpenPEARLesp32/prj/bootloader_support/libbootloader_support.a \
 /usr/local/lib/OpenPEARLesp32/prj/app_update/libapp_update.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_ipc/libesp_ipc.a \
 /usr/local/lib/OpenPEARLesp32/prj/spi_flash/libspi_flash.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_system/libesp_system.a \
 /usr/local/lib/OpenPEARLesp32/prj/soc/libsoc.a \
 /usr/local/lib/OpenPEARLesp32/prj/vfs/libvfs.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_eth/libesp_eth.a \
 /usr/local/lib/OpenPEARLesp32/prj/tcpip_adapter/libtcpip_adapter.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_netif/libesp_netif.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_event/libesp_event.a \
 /usr/local/lib/OpenPEARLesp32/prj/wpa_supplicant/libwpa_supplicant.a \
 /usr/local/lib/OpenPEARLesp32/prj/nvs_flash/libnvs_flash.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_wifi/libesp_wifi.a \
 /usr/local/lib/OpenPEARLesp32/prj/lwip/liblwip.a \
 /usr/local/lib/OpenPEARLesp32/prj/log/liblog.a \
 /usr/local/lib/OpenPEARLesp32/prj/heap/libheap.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_ringbuf/libesp_ringbuf.a \
 /usr/local/lib/OpenPEARLesp32/prj/driver/libdriver.a \
 /usr/local/lib/OpenPEARLesp32/prj/pthread/libpthread.a \
 /usr/local/lib/OpenPEARLesp32/prj/espcoredump/libespcoredump.a \
 /usr/local/lib/OpenPEARLesp32/prj/perfmon/libperfmon.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp32/libesp32.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_common/libesp_common.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_timer/libesp_timer.a \
 /usr/local/lib/OpenPEARLesp32/prj/freertos/libfreertos.a \
 /usr/local/lib/OpenPEARLesp32/prj/newlib/libnewlib.a \
 /usr/local/lib/OpenPEARLesp32/prj/cxx/libcxx.a \
 /usr/local/lib/OpenPEARLesp32/prj/app_trace/libapp_trace.a \
 /usr/local/lib/OpenPEARLesp32/prj/nghttp/libnghttp.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp-tls/libesp-tls.a \
 /usr/local/lib/OpenPEARLesp32/prj/tcp_transport/libtcp_transport.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_http_client/libesp_http_client.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_http_server/libesp_http_server.a \
 /usr/local/lib/OpenPEARLesp32/prj/ulp/libulp.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedtls.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedcrypto.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedx509.a \
 /usr/local/lib/OpenPEARLesp32/prj/soc/soc/esp32/libsoc_esp32.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcoexist.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcore.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libespnow.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libmesh.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libnet80211.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libpp.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/librtc.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libsmartconfig.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libphy.a \
 /usr/local/lib/OpenPEARLesp32/prj/xtensa/libxtensa.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/libmbedtls.a \
 /usr/local/lib/OpenPEARLesp32/prj/efuse/libefuse.a \
 /usr/local/lib/OpenPEARLesp32/prj/bootloader_support/libbootloader_support.a \
 /usr/local/lib/OpenPEARLesp32/prj/app_update/libapp_update.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_ipc/libesp_ipc.a \
 /usr/local/lib/OpenPEARLesp32/prj/spi_flash/libspi_flash.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_system/libesp_system.a \
 /usr/local/lib/OpenPEARLesp32/prj/soc/libsoc.a \
 /usr/local/lib/OpenPEARLesp32/prj/vfs/libvfs.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_eth/libesp_eth.a \
 /usr/local/lib/OpenPEARLesp32/prj/tcpip_adapter/libtcpip_adapter.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_netif/libesp_netif.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_event/libesp_event.a \
 /usr/local/lib/OpenPEARLesp32/prj/wpa_supplicant/libwpa_supplicant.a \
 /usr/local/lib/OpenPEARLesp32/prj/nvs_flash/libnvs_flash.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_wifi/libesp_wifi.a \
 /usr/local/lib/OpenPEARLesp32/prj/lwip/liblwip.a \
 /usr/local/lib/OpenPEARLesp32/prj/log/liblog.a \
 /usr/local/lib/OpenPEARLesp32/prj/heap/libheap.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_ringbuf/libesp_ringbuf.a \
 /usr/local/lib/OpenPEARLesp32/prj/driver/libdriver.a \
 /usr/local/lib/OpenPEARLesp32/prj/pthread/libpthread.a \
 /usr/local/lib/OpenPEARLesp32/prj/espcoredump/libespcoredump.a \
 /usr/local/lib/OpenPEARLesp32/prj/perfmon/libperfmon.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp32/libesp32.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_common/libesp_common.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_timer/libesp_timer.a \
 /usr/local/lib/OpenPEARLesp32/prj/freertos/libfreertos.a \
 /usr/local/lib/OpenPEARLesp32/prj/newlib/libnewlib.a \
 /usr/local/lib/OpenPEARLesp32/prj/cxx/libcxx.a \
 /usr/local/lib/OpenPEARLesp32/prj/app_trace/libapp_trace.a \
 /usr/local/lib/OpenPEARLesp32/prj/nghttp/libnghttp.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp-tls/libesp-tls.a \
 /usr/local/lib/OpenPEARLesp32/prj/tcp_transport/libtcp_transport.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_http_client/libesp_http_client.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_http_server/libesp_http_server.a \
 /usr/local/lib/OpenPEARLesp32/prj/ulp/libulp.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedtls.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedcrypto.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedx509.a \
 /usr/local/lib/OpenPEARLesp32/prj/soc/soc/esp32/libsoc_esp32.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcoexist.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcore.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libespnow.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libmesh.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libnet80211.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libpp.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/librtc.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libsmartconfig.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libphy.a \
 /usr/local/lib/OpenPEARLesp32/prj/xtensa/libxtensa.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/libmbedtls.a \
 /usr/local/lib/OpenPEARLesp32/prj/efuse/libefuse.a \
 /usr/local/lib/OpenPEARLesp32/prj/bootloader_support/libbootloader_support.a \
 /usr/local/lib/OpenPEARLesp32/prj/app_update/libapp_update.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_ipc/libesp_ipc.a \
 /usr/local/lib/OpenPEARLesp32/prj/spi_flash/libspi_flash.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_system/libesp_system.a \
 /usr/local/lib/OpenPEARLesp32/prj/soc/libsoc.a \
 /usr/local/lib/OpenPEARLesp32/prj/vfs/libvfs.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_eth/libesp_eth.a \
 /usr/local/lib/OpenPEARLesp32/prj/tcpip_adapter/libtcpip_adapter.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_netif/libesp_netif.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_event/libesp_event.a \
 /usr/local/lib/OpenPEARLesp32/prj/wpa_supplicant/libwpa_supplicant.a \
 /usr/local/lib/OpenPEARLesp32/prj/nvs_flash/libnvs_flash.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_wifi/libesp_wifi.a \
 /usr/local/lib/OpenPEARLesp32/prj/lwip/liblwip.a \
 /usr/local/lib/OpenPEARLesp32/prj/log/liblog.a \
 /usr/local/lib/OpenPEARLesp32/prj/heap/libheap.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_ringbuf/libesp_ringbuf.a \
 /usr/local/lib/OpenPEARLesp32/prj/driver/libdriver.a \
 /usr/local/lib/OpenPEARLesp32/prj/pthread/libpthread.a \
 /usr/local/lib/OpenPEARLesp32/prj/espcoredump/libespcoredump.a \
 /usr/local/lib/OpenPEARLesp32/prj/perfmon/libperfmon.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp32/libesp32.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_common/libesp_common.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_timer/libesp_timer.a \
 /usr/local/lib/OpenPEARLesp32/prj/freertos/libfreertos.a \
 /usr/local/lib/OpenPEARLesp32/prj/newlib/libnewlib.a \
 /usr/local/lib/OpenPEARLesp32/prj/cxx/libcxx.a \
 /usr/local/lib/OpenPEARLesp32/prj/app_trace/libapp_trace.a \
 /usr/local/lib/OpenPEARLesp32/prj/nghttp/libnghttp.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp-tls/libesp-tls.a \
 /usr/local/lib/OpenPEARLesp32/prj/tcp_transport/libtcp_transport.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_http_client/libesp_http_client.a \
 /usr/local/lib/OpenPEARLesp32/prj/esp_http_server/libesp_http_server.a \
 /usr/local/lib/OpenPEARLesp32/prj/ulp/libulp.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedtls.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedcrypto.a \
 /usr/local/lib/OpenPEARLesp32/prj/mbedtls/mbedtls/library/libmbedx509.a \
 /usr/local/lib/OpenPEARLesp32/prj/soc/soc/esp32/libsoc_esp32.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcoexist.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libcore.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libespnow.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libmesh.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libnet80211.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libpp.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/librtc.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libsmartconfig.a \
 /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32/libphy.a \
 /usr/local/lib/OpenPEARLesp32/idf/xtensa/esp32/libhal.a \
 -u esp_app_desc\
 -L /usr/local/lib/OpenPEARLesp32/idf/esp_rom/esp32/ld\
 -T esp32.rom.newlib-time.ld\
 -T esp32.rom.ld\
 -T esp32.rom.libgcc.ld\
 -T esp32.rom.newlib-data.ld\
 -T esp32.rom.syscalls.ld\
 -T esp32.rom.newlib-funcs.ld\
 -u vfs_include_syscalls_impl\
 -L /usr/local/lib/OpenPEARLesp32/idf/esp_wifi/lib/esp32\
 -u pthread_include_pthread_impl\
 -u pthread_include_pthread_cond_impl\
 -u pthread_include_pthread_local_storage_impl\
 -L /usr/local/lib/OpenPEARLesp32/prj/esp32\
 -T esp32_out.ld\
 -u app_main\
 -L /usr/local/lib/OpenPEARLesp32/prj/esp32/ld\
 -T esp32.project.ld\
 -L /usr/local/lib/OpenPEARLesp32/idf/esp32/ld\
 -T esp32.peripherals.ld\
 -u call_user_start_cpu0\
 -u ld_include_panic_highint_hdl\
 -Wl,--gc-sections\
 -Wl,--undefined=uxTopUsedPriority\
 -lm\
 /usr/local/lib/OpenPEARLesp32/prj/newlib/libnewlib.a \
 -u newlib_include_locks_impl\
 -u newlib_include_heap_impl\
 -u newlib_include_syscalls_impl\
 -u newlib_include_pthread_impl\
 -lgcc\
 -u __cxa_guard_dummy\
 -lstdc++\
 /usr/local/lib/OpenPEARLesp32/prj/pthread/libpthread.a \
 /usr/local/lib/OpenPEARLesp32/prj/app_trace/libapp_trace.a \
 -lgcov\
 /usr/local/lib/OpenPEARLesp32/prj/app_trace/libapp_trace.a \
 -lgcov\
 -lc\
 -lc\
