// [automatic generated by intermodule checker (imc v3) -- do not change ]
// 2021/07/13 11:51:36
// use of namespace is: false

#include "PearlIncludes.h" 



namespace pearlrt {
   int createSystemElements() {
	int nbrOfFails = 0;
	return nbrOfFails;
   }
}
