// [automatic generated by intermodule checker (imc v3) -- do not change ]
// 2021/07/09 19:34:45
// use of namespace is: false

#include "PearlIncludes.h" 





namespace pearlrt {
   int createSystemElements() {
	int nbrOfFails = 0;

	try {
	  // testprog.prl:3
	  static pearlrt::SendXML configurarion_0;
	  // testprog.prl:4
	  static pearlrt::Esp32WifiConfig configurarion_1((char*)" ", (char*)" ");

	} catch (pearlrt::Signal &s) {
	  nbrOfFails ++;
	}

	return nbrOfFails;
   }
}
