// [automatic generated by intermodule checker (imc v3) -- do not change ]
// 2021/05/21 13:41:58
// use of namespace is: false
#define TARGET 3
#include "PearlIncludes.h" 





namespace pearlrt {
   int createSystemElements() {
	int nbrOfFails = 0;

	try {
	  // Esp32WifiConfig.prl:3
	  static pearlrt::Esp32WifiConfig configurarion_0((char*)" ", (char*)" ");

	} catch (pearlrt::Signal &s) {
	  nbrOfFails ++;
	}

	return nbrOfFails;
   }
}
