// [automatic generated by intermodule checker (imc v3) -- do not change ]
// 2019/12/29 19:16:50
// use of namespace is: false

#include "PearlIncludes.h" 



namespace pearlrt {
   int createSystemElements();
}

// enshure that the static (parametrized) objects are instantiated first
static int dummy = pearlrt::createSystemElements();

	pearlrt::Device *  d_stdout;		// LogDemo.prl:9



namespace pearlrt {
   int createSystemElements() {
	// LogDemo.prl:9
	static pearlrt::StdOut s_stdout;
	d_stdout= &s_stdout;


	return 0;
   }
}
