\htgt{Declaration} ::=\\
\x \hlink{LengthDefinition} \\
\x $\mid$ \hlink{TypeDefinition}\\
\x $\mid$ \hlink{VariableDeclaration}\\
\x $\mid$ \hlink{FormatDeclaration}\\
\x $\mid$ \hlink{ProcedureDeclaration}\\
\x $\mid$ \hlink{TaskDeclaration}\\
%%%% added
\x $\mid$ \hlink{UserSignalDeclaration}
