\htgt{SchedulingSignalReaction} ::=\\
\x \kw{ON} \hlink{Name}$\S $Signal \{ \\
\x \x  \kw{RST} \kw{(} \hlink{Name}$\S $ErrorVariable-FIXED \kw{)} $\mid$ \\
\x \x [ \kw{RST} \kw{(} \hlink{Name}$\S $ErrorVariable-FIXED \kw{)} ] \kw{:} \\
\x \x \x \x \hlink{SignalReaction}  \\
\x   \} \kw{;} 

