// [automatic generated by intermodule checker (imc v3) -- do not change ]
// 2021/03/23 13:02:26
// use of namespace is: false

//#include "PearlIncludes.h" 





namespace pearlrt {
   int createSystemElements() {


	return 0;
   }
}
