/* DO NOT CHANGE */
/* generated by inter module checker (IMC) version 1.0*/


namespace pearlrt {
    int createSystemElements();
}
// ensure that the static (parametrized) objects are instanciated first
static int dummy = pearlrt::createSystemElements();

/* Forward declarations */



namespace pearlrt {
    int createSystemElements() {
        return 0;
    }
}
